### ISSUE TITLE
Key lanenet_model/vgg_backend/instance_seg/pix_bn/beta not found in checkpoint

### ISSUE THREAD

**Issue by winstxnhdw** [AbangLZU/LaneNetRos#17]
Dropbox link to the models are broken, so I took the models from the original LaneNet by @MaybeShewill-CV.

I used the requirements.txt but there is no such version for scikit_learn so I just installed the latest. 

I swapped the vgg16_based_fcn.py file with the LaneNet for Python2 and it's still broken. 

I suspect that the models from @MaybeShewill-CV are too new.

**Comment by ghost** [comment]
do maintainers of this repo have any plans to support the latest models? It appears they can no longer be restored.

**Comment by dkhanna511** [comment]
Hi, I have got the same error. I have also changed the vgg16_based_fcn.py from MaybeSheWeill-CV but the error did not change.

**Comment by winstxnhdw** [comment]
I have given up. This repository is probably long deprecated.

**Comment by HosikChae** [comment]
Have the same error. Thank you guys for saving my time.
Maybe, I need to write up my own version of a ROS node using the original LaneNet...
