### ISSUE TITLE
权重

### ISSUE THREAD

**Issue by zhangtiantian12311** [AbangLZU/LaneNetRos#2]
你好，我发现你给的官方的模型和你基于官方改编的ros代码，模型参数有所改变，请问是否可以将你用的模型分享，特别感谢

**Comment by AbangLZU** [comment]
I will update the code later.

**Comment by zhangtiantian12311** [comment]
Thank you very much

**Comment by AbangLZU** [comment]
> Thank you very much

I have just update the code to support the new model. you can try it.
