### ISSUE TITLE
您好您的权重链接不存在了，可以重新发一遍吗

### ISSUE THREAD

**Issue by FeiNoLabel** [AbangLZU/LaneNetRos#23]

**Comment by Nicoladao** [comment]
您好，请问您是怎么下载好的？

> _No description provided._

**Comment by FeiNoLabel** [comment]
> 您好，请问您是怎么下载好的？
> 
> > _No description provided._

我在laneNet的作者github中下载的，但是使用作者的权重并不能完成laneNet-ros的功能。会报错，你可以下载下来调试一番。祝你好运
