### ISSUE TITLE
Can you give the new download weights link

### ISSUE THREAD

**Issue by asimkymk** [AbangLZU/LaneNetRos#29]
Hello the weights file's link deleted and the original author of lanenet  had changed to weights file. but the new files could not be used for your ros node so i  need old weight files can you upload the files?

**Comment by bchampp** [comment]
https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0

**Comment by ajay1606** [comment]
@asimkymk Have you been able to run the ROS node successfully with these [weights file](https://www.dropbox.com/sh/0b6r0ljqi76kyg9/AADedYWO3bnx4PhK1BmbJkJKa?dl=0) ?

I am still getting errors with these weights files. Could you please help me, if you have already solved this ?

Appreciate any response.
